const AVATAR_WIDTH = 74
const AVATAR_HORIZONTAL_MARGIN = 6
const AVATAR_LIST_ITEM_WIDTH = AVATAR_WIDTH + AVATAR_HORIZONTAL_MARGIN * 2

export default {
  AVATAR_WIDTH,
  AVATAR_HORIZONTAL_MARGIN,
  AVATAR_LIST_ITEM_WIDTH,
}
